/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import supervisiontracker.SupervisionCore;

/**
 *
 * @author Sergiu Borlovan <sergiuborlovan.co.uk>
 */
public class SupervisionTrackerGUI extends javax.swing.JFrame {

    /**
     * Creates new form SupervisionTrackerGUI
     */
    public SupervisionTrackerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffList = new javax.swing.ButtonGroup();
        supervisorList = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rButtonSergiu = new javax.swing.JRadioButton();
        rButtonSharon = new javax.swing.JRadioButton();
        rButtonSue = new javax.swing.JRadioButton();
        rButtonTracy = new javax.swing.JRadioButton();
        rButtonRobert = new javax.swing.JRadioButton();
        rButtonSam = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        rButtonBob = new javax.swing.JRadioButton();
        rButtonReju = new javax.swing.JRadioButton();
        rButtonDavid = new javax.swing.JRadioButton();
        rButtonStephen = new javax.swing.JRadioButton();
        rButtonJohn = new javax.swing.JRadioButton();
        rButtonJonty = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputPane = new javax.swing.JTextPane();
        saveButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSupervisorMichael = new javax.swing.JRadioButton();
        rSupervisorSharon = new javax.swing.JRadioButton();
        rSupervisorSergiu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supervison Tracker");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Staff list"));

        staffList.add(rButtonSergiu);
        rButtonSergiu.setText("Sergiu");
        rButtonSergiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonSergiuActionPerformed(evt);
            }
        });

        staffList.add(rButtonSharon);
        rButtonSharon.setText("Sharon");
        rButtonSharon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonSharonActionPerformed(evt);
            }
        });

        staffList.add(rButtonSue);
        rButtonSue.setText("Sue");
        rButtonSue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonSueActionPerformed(evt);
            }
        });

        staffList.add(rButtonTracy);
        rButtonTracy.setText("Tracy");
        rButtonTracy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonTracyActionPerformed(evt);
            }
        });

        staffList.add(rButtonRobert);
        rButtonRobert.setText("Robert");
        rButtonRobert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonRobertActionPerformed(evt);
            }
        });

        staffList.add(rButtonSam);
        rButtonSam.setText("Sam");
        rButtonSam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonSamActionPerformed(evt);
            }
        });

        jButton2.setText("Edit staff list");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        staffList.add(rButtonBob);
        rButtonBob.setText("Bob");
        rButtonBob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonBobActionPerformed(evt);
            }
        });

        staffList.add(rButtonReju);
        rButtonReju.setText("Reju");
        rButtonReju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonRejuActionPerformed(evt);
            }
        });

        staffList.add(rButtonDavid);
        rButtonDavid.setText("David");
        rButtonDavid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonDavidActionPerformed(evt);
            }
        });

        staffList.add(rButtonStephen);
        rButtonStephen.setText("Stephen");
        rButtonStephen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonStephenActionPerformed(evt);
            }
        });

        staffList.add(rButtonJohn);
        rButtonJohn.setText("John");
        rButtonJohn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonJohnActionPerformed(evt);
            }
        });

        staffList.add(rButtonJonty);
        rButtonJonty.setText("Jonty");
        rButtonJonty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonJontyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rButtonSergiu)
                            .addComponent(rButtonSharon)
                            .addComponent(rButtonSue)
                            .addComponent(rButtonTracy)
                            .addComponent(rButtonRobert)
                            .addComponent(rButtonSam)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rButtonBob))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rButtonReju))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rButtonDavid))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rButtonStephen))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rButtonJohn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rButtonJonty)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rButtonSergiu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonSharon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonSue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonTracy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonRobert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonSam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonBob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonReju)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonDavid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonStephen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonJohn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButtonJonty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Supervision notes"));

        jScrollPane2.setViewportView(outputPane);

        saveButton.setText("save notes");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add supervision"));

        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });

        jLabel1.setText("Date:");

        jLabel2.setText("Supervisor:");

        supervisorList.add(rSupervisorMichael);
        rSupervisorMichael.setText("Michael");
        rSupervisorMichael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSupervisorMichaelActionPerformed(evt);
            }
        });

        supervisorList.add(rSupervisorSharon);
        rSupervisorSharon.setText("Sharon");
        rSupervisorSharon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSupervisorSharonActionPerformed(evt);
            }
        });

        supervisorList.add(rSupervisorSergiu);
        rSupervisorSergiu.setText("Sergiu");
        rSupervisorSergiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSupervisorSergiuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSupervisorMichael)
                .addGap(18, 18, 18)
                .addComponent(rSupervisorSharon)
                .addGap(18, 18, 18)
                .addComponent(rSupervisorSergiu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(rSupervisorMichael)
                    .addComponent(rSupervisorSharon)
                    .addComponent(rSupervisorSergiu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        SupervisionCore core = new SupervisionCore();
        String selected = null;
        String key;
        String notes;
        for (Enumeration<AbstractButton> buttons = staffList.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                selected =  button.getText();
            }
        }
        key = "supervisionTracker" + selected + "Notes";

        notes = outputPane.getText();
        core.setSupervisionNotes(key, notes);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void rButtonSergiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonSergiuActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerSergiuNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonSergiuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // code
    }//GEN-LAST:event_formWindowOpened

    private void rButtonSharonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonSharonActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerSharonNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonSharonActionPerformed

    private void rButtonSueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonSueActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerSueNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonSueActionPerformed

    private void rButtonTracyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonTracyActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerTracyNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonTracyActionPerformed

    private void rButtonRobertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonRobertActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerRobertNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonRobertActionPerformed

    private void rButtonSamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonSamActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerSamNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonSamActionPerformed

    private void rButtonBobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonBobActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerBobNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonBobActionPerformed

    private void rButtonRejuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonRejuActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerRejuNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonRejuActionPerformed

    private void rButtonDavidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonDavidActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerRejuNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonDavidActionPerformed

    private void rButtonStephenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonStephenActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerStephenNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonStephenActionPerformed

    private void rButtonJohnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonJohnActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerJohnNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonJohnActionPerformed

    private void rButtonJontyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonJontyActionPerformed
        SupervisionCore core = new SupervisionCore();
        String text = core.getSupervisionNotes("supervisionTrackerJontyNotes");
        outputPane.setText(text);
    }//GEN-LAST:event_rButtonJontyActionPerformed

    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        String currentNotes = outputPane.getText();
        String date = datePicker.getDate().toString();
        String newNotes = currentNotes + "\n" + date.substring(0,10) + ", " +date.substring(24, 28) + ":";
        
        outputPane.setText(newNotes);
    }//GEN-LAST:event_datePickerActionPerformed

    private void rSupervisorMichaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSupervisorMichaelActionPerformed
        String currentNotes = outputPane.getText();
        String newNotes = currentNotes + " by Michael.";
        outputPane.setText(newNotes);
    }//GEN-LAST:event_rSupervisorMichaelActionPerformed

    private void rSupervisorSharonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSupervisorSharonActionPerformed
        String currentNotes = outputPane.getText();
        String newNotes = currentNotes + " by Sharon.";
        outputPane.setText(newNotes);
    }//GEN-LAST:event_rSupervisorSharonActionPerformed

    private void rSupervisorSergiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSupervisorSergiuActionPerformed
        String currentNotes = outputPane.getText();
        String newNotes = currentNotes + " by Sergiu.";
        outputPane.setText(newNotes);
    }//GEN-LAST:event_rSupervisorSergiuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Feature under development.");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupervisionTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupervisionTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupervisionTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupervisionTrackerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupervisionTrackerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane outputPane;
    private javax.swing.JRadioButton rButtonBob;
    private javax.swing.JRadioButton rButtonDavid;
    private javax.swing.JRadioButton rButtonJohn;
    private javax.swing.JRadioButton rButtonJonty;
    private javax.swing.JRadioButton rButtonReju;
    private javax.swing.JRadioButton rButtonRobert;
    private javax.swing.JRadioButton rButtonSam;
    private javax.swing.JRadioButton rButtonSergiu;
    private javax.swing.JRadioButton rButtonSharon;
    private javax.swing.JRadioButton rButtonStephen;
    private javax.swing.JRadioButton rButtonSue;
    private javax.swing.JRadioButton rButtonTracy;
    private javax.swing.JRadioButton rSupervisorMichael;
    private javax.swing.JRadioButton rSupervisorSergiu;
    private javax.swing.JRadioButton rSupervisorSharon;
    private javax.swing.JButton saveButton;
    private javax.swing.ButtonGroup staffList;
    private javax.swing.ButtonGroup supervisorList;
    // End of variables declaration//GEN-END:variables
}
